# VIẾT THEO CÚ PHÁP YAML, CHÚ Ý CHÍNH XÁC KHOẢNG TRẮNG ĐẦU CÁC DÒNG
version: '3'                                 # Chỉ ra phiên bản docker-compose muốn sử dụng

services:                                    # CÁC DỊCH VỤ (CONTAINER) NĂM TRONG services
  # Database
  db:                                        # Tạo dịch vụ database
    image: mysql:5.7                         # Image tạo ra dịch vụ
    volumes:
      - db_data:/var/lib/mysql               # thư mục lưu DB
    restart: always                          # Restart container khi có lỗi
    environment:                             # Cài đặt biến môi trường theo hướng dẫn
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:                                # nối vào mạng my-network (tạo mạng này ở dưới)
      - wpsite
  #phpmyadmin
  phpmyadmin:                                # Tạo dịch vụ phpmyadmin
    depends_on:                              # Chỉ ra sự phụ thuộc. Service db chạy xong thì service này mới được chạy
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:                                   # Thiết lập cổng để ánh xạ
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password 
    networks:
      - wpsite
  # Wordpress
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - '8000:80'
    restart: always
    volumes: ['./:/var/www/html']
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    networks:
      - wpsite
networks:                                     # TẠO NETWORK
  wpsite:
volumes:                                      # TẠO Ổ Đĩa
  db_data: